---
name: Deploy To Production

on:
  # Use only for faster testing
  # push:
  #   branches:
  #     - master

  release:
    types:
      - released

  # push:
  #   tags:
  #     - "**"

  # pull_request:
  #   branches:
  #     - master

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - run: dotnet publish -p:PublishProfile=FolderProfile

      - name: compress the build
        run: |
          powershell Compress-Archive -Path bin/MemeBox/* -DestinationPath MemeBox.zip

      - name: Get the verison
        id: get_version
        run: |
          echo "VERSION=$(cat app.xml | grep -oPm1 "(?<=<version>)[^<]+")" >> "$GITHUB_OUTPUT"

      - name: Get latest release
        id: get_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL=$(gh api repos/:owner/:repo/releases/latest --jq .upload_url)
          echo "RELEASE_URL=$RELEASE_URL" >> "$GITHUB_OUTPUT"
          LATEST_RELEASE_ID=$(gh api repos/:owner/:repo/releases/latest --jq .id)
          echo "latest_release_id=$LATEST_RELEASE_ID" >> "$GITHUB_OUTPUT"

      - name: Attach build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.RELEASE_URL }}
          asset_path: ./MemeBox.zip
          asset_name: MemeBox-v${{ steps.get_version.outputs.VERSION}}.zip
          asset_content_type: application/zip

      - uses: actions/upload-artifact@v4
        with:
          name: memebox-artifact
          path: MemeBox.zip

      - uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/download-artifact@v4
        with:
          name: memebox-artifact
          path: MemeBox.zip

      - uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: app.xml

      - name: scp zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "MemeBox.zip"
          target: "${{ secrets.PATH_TO_PROJECT}}/download"
          strip_components: 1

      - name: scp app.xml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "app.xml"
          target: "${{ secrets.PATH_TO_PROJECT}}"
          strip_components: 1
