---
name: Deploy To Production

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - run: dotnet publish -p:PublishProfile=FolderProfile

      - name: compress the build
        run: |
          powershell Compress-Archive -Update -Path bin/MemeBox/* -DestinationPath bin/MemeBox.zip

      - name: Download Pscp
        run: |
          Invoke-WebRequest -Uri "https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe" -OutFile "pscp.exe"
        
      - name: Copy to zip server
        run: |
          .\pscp.exe -i ${{ secrets.KEY }} -P ${{ secrets.PORT }} -r bin/MemeBox.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PATH_TO_PROJECT }}/download

      - name: Copy app.xml to server
        run: |
          .\pscp.exe -i ${{ secrets.KEY }} -P ${{ secrets.PORT }} -r app.xml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PATH_TO_PROJECT }}

      # - name: scp zip to server
      #   uses: appleboy/scp-action@master
      #   with:
      #       host: ${{ secrets.HOST }}
      #       username: ${{ secrets.USERNAME }}
      #       key: ${{ secrets.KEY }}
      #       port: ${{ secrets.PORT }}
      #       source: "bin/MemeBox/MemeBox.zip"
      #       target: "${{ secrets.PATH_TO_PROJECT}}/download"
      #       strip_components: 2
            
      # - name: scp app.xml to server
      #   uses: appleboy/scp-action@master
      #   with:
      #       host: ${{ secrets.HOST }}
      #       username: ${{ secrets.USERNAME }}
      #       key: ${{ secrets.KEY }}
      #       port: ${{ secrets.PORT }}
      #       source: "app.xml"
      #       target: "${{ secrets.PATH_TO_PROJECT}}"
