---
name: Deploy To Production

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - run: dotnet publish -p:PublishProfile=FolderProfile

      - name: compress the build
        run: |
          powershell Compress-Archive -Path bin/MemeBox/* -DestinationPath MemeBox.zip

      - uses: actions/upload-artifact@v2
        with:
          name: MemeBox.zip
          path: MemeBox.zip

      - uses: actions/upload-artifact@v2
        with:
          name: app.xml
          path: app.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: MemeBox.zip
          path: MemeBox.zip
      
      - uses: actions/download-artifact@v2
        with:
          name: app.xml
          path: app.xml

      - name: scp zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "MemeBox.zip"
          target: "${{ secrets.PATH_TO_PROJECT}}/download"
          strip_components: 2

      - name: scp app.xml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "app.xml"
          target: "${{ secrets.PATH_TO_PROJECT}}"
